### ISSUE TITLE
Can't extract tar nor compile the file

### ISSUE THREAD

**Issue by pires22** [ctn-malone/websocketd-controller#1]
I'm using Ubuntu 18.04.5 LTS in a vm.

First issue when I run the command:

tar -xf websocketd-controller.x86_64.xz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Second issue: I cloned the repo and tried to compile the .js file but got this error: "ReferenceError: could not load module filename 'ext/arg.js"

**Comment by ctn-malone** [comment]
Can you try doing `xz -d websocketd-controller.x86_64.xz` instead ?

**Comment by ctn-malone** [comment]
If you want to compile it, you'll need to use https://github.com/ctn-malone/quickjs-cross-compiler/releases/tag/2021-03-27_2%2Bext-lib-0.4.0 which comes bundled with https://github.com/ctn-malone/qjs-ext-lib.

Another alternative (if you want to use vanilla quickjs)

* checkout https://github.com/ctn-malone/websocketd-controller.git
```
git checkout https://github.com/ctn-malone/websocketd-controller.git
```
* checkout https://github.com/ctn-malone/qjs-ext-lib
```
git checkout https://github.com/ctn-malone/qjs-ext-lib.git
```
* create a symlink for qjs-ext-lib/src under websocketd-controller repository
```
cd websocketd-controller && ln -s ../../qjs-ext-lib/src src/ext
```
* compile file
```
qjsc -o websocketd-controller src/websocketd-controller.js
```

**Comment by pires22** [comment]
Thanks @ctn-malone, I managed to compile it using the quickjs version you sent the link, it is running fine.

But I noticed that the task only runs if I have a websocket connection open, is there any way to keep the program running forever and when I go to the link I just get access to the STDERR and STDOUT that it is sending?

**Comment by ctn-malone** [comment]
Unfortunately, no. That's the way [websocketd](https://github.com/joewalnes/websocketd) works :

- it starts the process on websocket connection
- it stops the process on websocket disconnection
- it closes the websocket if the process exits

**Comment by ctn-malone** [comment]
@pires22 : what you could do, is something like this :
* start the program manually and redirect stdout and stderr to a file
```
myprog &>/tmp/log.txt
``` 
* run a `tail` command using `websocketd`
```
tail -f /tmp/log.txt
```
This way every time you open a websocket connection, you'll see the last output of the program

**Comment by pires22** [comment]
I figured a way already, thanks for you help! @ctn-malone
